<?xml version="1.0"?>
<robot name="rc_car" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Basic dimensions -->
  <xacro:property name="chassis_length" value="0.46"/>
  <xacro:property name="chassis_width" value="0.28"/>
  <xacro:property name="chassis_height" value="0.10"/>
  <xacro:property name="chassis_clearance" value="0.03"/>
  <xacro:property name="wheel_radius" value="0.06"/>
  <xacro:property name="wheel_thickness" value="0.03"/>

  <!-- Placement helpers -->
  <xacro:property name="wheel_base_x" value="${chassis_length / 2.0 - 0.07}"/>
  <xacro:property name="wheel_track_y" value="${chassis_width / 2.0 + wheel_thickness / 2.0 - 0.01}"/>
  <xacro:property name="axle_height" value="${wheel_radius}"/>

  <!-- Mass and inertia approximations -->
  <xacro:property name="chassis_mass" value="3.0"/>
  <xacro:property name="wheel_mass" value="0.25"/>
  <xacro:property name="steer_mass" value="0.05"/>

  <xacro:property name="chassis_ixx" value="${chassis_mass / 12.0 * (chassis_height*chassis_height + chassis_width*chassis_width)}"/>
  <xacro:property name="chassis_iyy" value="${chassis_mass / 12.0 * (chassis_length*chassis_length + chassis_height*chassis_height)}"/>
  <xacro:property name="chassis_izz" value="${chassis_mass / 12.0 * (chassis_length*chassis_length + chassis_width*chassis_width)}"/>

  <xacro:property name="wheel_ixx" value="${wheel_mass / 12.0 * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}"/>
  <xacro:property name="wheel_iyy" value="${wheel_ixx}"/>
  <xacro:property name="wheel_izz" value="${0.5 * wheel_mass * wheel_radius * wheel_radius}"/>

  <!-- Materials -->
  <material name="chassis_grey">
    <color rgba="0.27 0.27 0.3 1.0"/>
  </material>
  <material name="wheel_black">
    <color rgba="0.05 0.05 0.05 1.0"/>
  </material>

  <xacro:macro name="wheel" params="name parent xyz">
    <link name="${name}">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${wheel_mass}"/>
        <inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${wheel_iyy}" iyz="0.0" izz="${wheel_izz}"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
        <material name="wheel_black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <origin xyz="${xyz}" rpy="1.5708 0 0"/>
      <axis xyz="0 0 1"/>
    </joint>
    <gazebo reference="${name}">
      <mu1>1.2</mu1>
      <mu2>1.2</mu2>
      <kp>80000.0</kp>
      <kd>20.0</kd>
    </gazebo>
  </xacro:macro>

  <xacro:macro name="steered_wheel" params="name parent xyz">
    <link name="${name}_steer">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${steer_mass}"/>
        <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0002"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.01" length="0.04"/>
        </geometry>
        <material name="chassis_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.01" length="0.04"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_steer_joint" type="revolute">
      <parent link="${parent}"/>
      <child link="${name}_steer"/>
      <origin xyz="${xyz}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.6" upper="0.6" effort="10.0" velocity="1.5"/>
    </joint>
    <xacro:wheel name="${name}" parent="${name}_steer" xyz="0 0 0"/>
  </xacro:macro>

  <link name="base_link">
    <inertial>
      <origin xyz="0 0 ${chassis_height / 2.0 + chassis_clearance}" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="${chassis_ixx}" ixy="0.0" ixz="0.0" iyy="${chassis_iyy}" iyz="0.0" izz="${chassis_izz}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 ${chassis_height / 2.0 + chassis_clearance}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="chassis_grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${chassis_height / 2.0 + chassis_clearance}" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <link name="lidar_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.05"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.02" length="0.03"/>
      </geometry>
      <material name="chassis_grey"/>
    </visual>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${chassis_length/2 - 0.05} 0 ${chassis_height/2 + 0.08}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <always_on>true</always_on>
      <update_rate>12</update_rate>
      <visualize>true</visualize>
      <topic>/scan</topic>
      <lidar>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159265</min_angle>
            <max_angle>3.14159265</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.05</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise type="gaussian">
          <mean>0.0</mean>
          <stddev>0.0</stddev>
        </noise>
      </lidar>
    </sensor>
  </gazebo>

  <xacro:steered_wheel name="front_left_wheel" parent="base_link" xyz="${wheel_base_x} ${wheel_track_y} ${axle_height}"/>
  <xacro:steered_wheel name="front_right_wheel" parent="base_link" xyz="${wheel_base_x} ${-wheel_track_y} ${axle_height}"/>
  <xacro:wheel name="rear_left_wheel" parent="base_link" xyz="${-wheel_base_x} ${wheel_track_y} ${axle_height}"/>
  <xacro:wheel name="rear_right_wheel" parent="base_link" xyz="${-wheel_base_x} ${-wheel_track_y} ${axle_height}"/>

  <ros2_control name="rc_car_system" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_left_wheel_steer_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_wheel_steer_joint">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so"/>
  </gazebo>

  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
    <mu1>1.2</mu1>
    <mu2>1.2</mu2>
    <kp>80000.0</kp>
    <kd>20.0</kd>
  </gazebo>

  <gazebo>
    <plugin
      filename="gz-sim-joint-controller-system"
      name="gz::sim::systems::JointController">
      <joint_name>rear_left_wheel_joint</joint_name>
    </plugin>
    <plugin
      filename="gz-sim-joint-controller-system"
      name="gz::sim::systems::JointController">
      <joint_name>rear_right_wheel_joint</joint_name>
    </plugin>
    <plugin
      filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>front_left_wheel_steer_joint</joint_name>
      <topic>/model/rc_car/joint/front_left_wheel_steer_joint/cmd_pos</topic>
      <p_gain>20.0</p_gain>
      <i_gain>0.1</i_gain>
      <d_gain>0.5</d_gain>
      <cmd_max>0.6</cmd_max>
      <cmd_min>-0.6</cmd_min>
    </plugin>
    <plugin
      filename="gz-sim-joint-position-controller-system"
      name="gz::sim::systems::JointPositionController">
      <joint_name>front_right_wheel_steer_joint</joint_name>
      <topic>/model/rc_car/joint/front_right_wheel_steer_joint/cmd_pos</topic>
      <p_gain>20.0</p_gain>
      <i_gain>0.1</i_gain>
      <d_gain>0.5</d_gain>
      <cmd_max>0.6</cmd_max>
      <cmd_min>-0.6</cmd_min>
    </plugin>
  </gazebo>
</robot>
